[package]
name = "aoc"
version = "0.1.0"
authors = ["Ske <ske@ske.pw>"]

[dependencies]
md5 = "0.1.1"
regex = "0.1.43"
bit-vec = "0.4.2"
serde_json = "0.6.0"
permutohedron = "0.1.7"
itertools = "0.4.3"
